#!/bin/bash
declare -p SOURCE_BRANCH SOURCE_COMMIT COMMIT_MSG DOCKER_REPO DOCKERFILE_PATH DOCKER_TAG IMAGE_NAME
set -e
set -o pipefail
v=$(docker run $IMAGE_NAME ansible --version | grep -Eom1 '[0-9][0-9\.]+')
if [[ -n $v ]]; then
  set -x
  docker tag "$IMAGE_NAME" "$DOCKER_REPO:$v"
  docker push "$DOCKER_REPO:$v"
fi
